name: my_loguru
env:
  VERSION: "0.0.2"

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install build dependencies
      run: python -m pip install -U setuptools wheel build twine
    - name: Build
      run: python -m build .
    - name: Publish
      run: python -m twine upload dist/* --verbose -u __token__ -p ${{ secrets.PYPI_PASSWORD }}
